cd ../../../
pwd
g++ -g -std=c++17 -o mysql_proxy/src/cpp_wrapper/libopen.so \
  mysql_proxy/src/cpp_wrapper/open.cpp \
  -shared \
  -fPIC \
	-Wl,-rpath,$(pwd)/bazel-out/k8-fastbuild/bin/_solib_k8/_U_S_Spelton_Splanner_Cplanner___Ulib_Sjli \
	-Wl,-rpath,$(pwd)/bazel-out/k8-fastbuild/bin/_solib_k8/_U_S_Spelton_Splanner_Cplanner___Ulib \
	-Wl,-rpath,$(pwd)/bazel-out/k8-fastbuild/bin/_solib_k8/_U_S_Spelton_Splanner_Cplanner___Ulib_Sserver \
	-Lbazel-out/k8-fastbuild/bin/_solib_k8/_U_S_Spelton_Splanner_Cplanner___Ulib_Sjli \
	-Lbazel-out/k8-fastbuild/bin/_solib_k8/_U_S_Spelton_Splanner_Cplanner___Ulib \
	-Lbazel-out/k8-fastbuild/bin/_solib_k8/_U_S_Spelton_Splanner_Cplanner___Ulib_Sserver \
	-Wl,-S \
	-fuse-ld=gold \
	-Wl,-no-as-needed \
	-Wl,-z,relro,-z,now \
	-B/usr/bin \
	-pass-exit-codes \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/_objs/pelton/pelton.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/engine/engine.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/create/create.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/update/update.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/delete/delete.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/insert/insert.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/select/select.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/index/index.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/view/view.pic.o \
	-Wl,--end-lib \
	-ljli \
	-latk-wrapper \
	-lattach \
	-lawt \
	-lawt_headless \
	-lawt_xawt \
	-ldt_socket \
	-lextnet \
	-lfontmanager \
	-linstrument \
	-lj2gss \
	-lj2pcsc \
	-lj2pkcs11 \
	-ljaas \
	-ljava \
	-ljavajpeg \
	-ljawt \
	-ljdwp \
	-ljimage \
	-ljsig \
	-ljsound \
	-llcms \
	-lmanagement \
	-lmanagement_agent \
	-lmanagement_ext \
	-lmlib_image \
	-lnet \
	-lnio \
	-lprefs \
	-lrmi \
	-lsaproc \
	-lsctp \
	-lsplashscreen \
	-lsunec \
	-lunpack \
	-lverify \
	-lzip \
	-ljsig \
	-ljvm \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/planner/_objs/planner/planner.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/_objs/state/state.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/_objs/graph/graph.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/ops/_objs/matview/matview.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/ops/_objs/grouped_data/grouped_data.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/hash/_objs/hash/hash.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/hash/_objs/city/city.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/container/_objs/raw_hash_set/raw_hash_set.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/container/_objs/hashtablez_sampler/hashtablez_sampler.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/container/_objs/hashtablez_sampler/hashtablez_sampler_force_weak_definition.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/exponential_biased/exponential_biased.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/synchronization/_objs/synchronization/barrier.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/synchronization/_objs/synchronization/blocking_counter.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/synchronization/_objs/synchronization/create_thread_identity.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/synchronization/_objs/synchronization/per_thread_sem.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/synchronization/_objs/synchronization/waiter.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/synchronization/_objs/synchronization/notification.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/synchronization/_objs/synchronization/mutex.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/synchronization/_objs/graphcycles_internal/graphcycles.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/_objs/time/civil_time.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/_objs/time/clock.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/_objs/time/duration.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/_objs/time/format.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/_objs/time/time.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/time_zone_fixed.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/time_zone_format.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/time_zone_if.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/time_zone_impl.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/time_zone_info.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/time_zone_libc.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/time_zone_lookup.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/time_zone_posix.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/time_zone/zone_info_source.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/time/internal/cctz/_objs/civil_time/civil_time_detail.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/ops/_objs/input/input.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/_objs/operator/operator.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/benchmark.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/benchmark_api_internal.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/benchmark_name.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/benchmark_register.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/benchmark_runner.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/colorprint.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/commandlineflags.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/complexity.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/console_reporter.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/counter.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/csv_reporter.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/json_reporter.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/reporter.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/sleep.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/statistics.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/string_util.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/sysinfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/gbenchmark/_objs/benchmark/timers.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/_objs/state/load.pic.o \
	bazel-out/k8-fastbuild/bin/pelton/shards/_objs/state/state.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/_objs/pool/pool.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/mysql/_objs/result/result.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/mysql/_objs/util/util.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/_objs/record/record.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/_objs/key/key.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/_objs/value/value.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/dataflow/_objs/schema/schema.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/util/_objs/fs/fs.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/sqlast/_objs/parser/parser.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/sqlast/_objs/hacky/hacky.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/sqlast/_objs/transformer/transformer.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/sqlast/_objs/ast/ast_expressions.pic.o \
	bazel-out/k8-fastbuild/bin/pelton/sqlast/_objs/ast/ast_schema.pic.o \
	bazel-out/k8-fastbuild/bin/pelton/sqlast/_objs/ast/ast_statements.pic.o \
	bazel-out/k8-fastbuild/bin/pelton/sqlast/_objs/ast/ast_visitors.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/status/_objs/statusor/statusor.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/types/_objs/bad_variant_access/bad_variant_access.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/grammars-v4/_pic_objs/sqlparser/sqlgrammar/sqlparser/SQLiteLexer.pic.o \
	bazel-out/k8-fastbuild/bin/external/grammars-v4/_pic_objs/sqlparser/sqlgrammar/sqlparser/SQLiteParser.pic.o \
	bazel-out/k8-fastbuild/bin/external/grammars-v4/_pic_objs/sqlparser/sqlgrammar/sqlparser/SQLiteParserBaseListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/grammars-v4/_pic_objs/sqlparser/sqlgrammar/sqlparser/SQLiteParserBaseVisitor.pic.o \
	bazel-out/k8-fastbuild/bin/external/grammars-v4/_pic_objs/sqlparser/sqlgrammar/sqlparser/SQLiteParserListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/grammars-v4/_pic_objs/sqlparser/sqlgrammar/sqlparser/SQLiteParserVisitor.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ANTLRErrorListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ANTLRErrorStrategy.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ANTLRFileStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ANTLRInputStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/BailErrorStrategy.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/BaseErrorListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/BufferedTokenStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/CharStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/CommonToken.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/CommonTokenFactory.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/CommonTokenStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ConsoleErrorListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/DefaultErrorStrategy.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/DiagnosticErrorListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Exceptions.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/FailedPredicateException.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/InputMismatchException.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/IntStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/InterpreterRuleContext.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Lexer.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerInterpreter.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerNoViableAltException.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ListTokenSource.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/NoViableAltException.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Parser.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParserInterpreter.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParserRuleContext.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ProxyErrorListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RecognitionException.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Recognizer.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RuleContext.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RuleContextWithAltNum.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RuntimeMetaData.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Token.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TokenSource.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TokenStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TokenStreamRewriter.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/UnbufferedCharStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/UnbufferedTokenStream.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Vocabulary.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/WritableToken.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ATN.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ATNConfig.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ATNConfigSet.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ATNDeserializationOptions.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ATNDeserializer.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ATNSerializer.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ATNSimulator.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ATNState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/AbstractPredicateTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ActionTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/AmbiguityInfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ArrayPredictionContext.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/AtomTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/BasicBlockStartState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/BasicState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/BlockEndState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/BlockStartState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ContextSensitivityInfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/DecisionEventInfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/DecisionInfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/DecisionState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/EmptyPredictionContext.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/EpsilonTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ErrorInfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LL1Analyzer.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerATNConfig.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerATNSimulator.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerActionExecutor.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerChannelAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerCustomAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerIndexedCustomAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerModeAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerMoreAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerPopModeAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerPushModeAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerSkipAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerTypeAction.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LookaheadEventInfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LoopEndState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/NotSetTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/OrderedATNConfigSet.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParseInfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParserATNSimulator.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/PlusBlockStartState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/PlusLoopbackState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/PrecedencePredicateTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/PredicateEvalInfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/PredicateTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/PredictionContext.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/PredictionMode.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ProfilingATNSimulator.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RangeTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RuleStartState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RuleStopState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RuleTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/SemanticContext.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/SetTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/SingletonPredictionContext.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/StarBlockStartState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/StarLoopEntryState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/StarLoopbackState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TokensStartState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Transition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/WildcardTransition.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/DFA.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/DFASerializer.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/DFAState.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/LexerDFASerializer.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/InterpreterDataReader.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Interval.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/IntervalSet.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/MurmurHash.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Predicate.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Any.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Arrays.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/CPPUtils.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/StringUtils.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/guid.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ErrorNode.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ErrorNodeImpl.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/IterativeParseTreeWalker.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParseTree.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParseTreeListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParseTreeVisitor.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParseTreeWalker.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TerminalNode.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TerminalNodeImpl.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Trees.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/Chunk.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParseTreeMatch.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParseTreePattern.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/ParseTreePatternMatcher.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/RuleTagToken.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TagChunk.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TextChunk.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/TokenTagToken.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPath.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathElement.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathLexer.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathLexerErrorListener.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathRuleAnywhereElement.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathRuleElement.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathTokenAnywhereElement.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathTokenElement.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathWildcardAnywhereElement.pic.o \
	bazel-out/k8-fastbuild/bin/external/antlr4_runtimes/_objs/cpp/XPathWildcardElement.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/shards/sqlengine/_objs/util/util.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/status/_objs/status/status.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/status/_objs/status/status_payload_printer.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/debugging/_objs/stacktrace/stacktrace.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/debugging/_objs/symbolize/symbolize.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/debugging/_objs/debugging_internal/address_is_readable.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/debugging/_objs/debugging_internal/elf_mem_image.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/debugging/_objs/debugging_internal/vdso_support.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/debugging/_objs/demangle_internal/demangle.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/malloc_internal/low_level_alloc.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/cord/cord.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/str_format_internal/arg.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/str_format_internal/bind.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/str_format_internal/extension.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/str_format_internal/float_conversion.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/str_format_internal/output.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/str_format_internal/parser.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/types/_objs/bad_optional_access/bad_optional_access.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/ascii.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/charconv.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/escaping.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/charconv_bigint.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/charconv_parse.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/memutil.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/match.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/numbers.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/str_cat.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/str_replace.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/str_split.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/string_view.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/strings/substitute.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/internal/escaping.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/internal/ostringstream.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/strings/_objs/internal/utf8.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/base/cycleclock.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/base/spinlock.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/base/sysinfo.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/base/thread_identity.pic.o \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/base/unscaledcycleclock.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/spinlock_wait/spinlock_wait.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/throw_delegate/throw_delegate.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/raw_logging_internal/raw_logging.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/base/_objs/log_severity/log_severity.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/absl/absl/numeric/_objs/int128/int128.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/pelton/util/_objs/perf/perf.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
	bazel-out/k8-fastbuild/bin/external/glog/_objs/glog/demangle.pic.o \
	bazel-out/k8-fastbuild/bin/external/glog/_objs/glog/logging.pic.o \
	bazel-out/k8-fastbuild/bin/external/glog/_objs/glog/raw_logging.pic.o \
	bazel-out/k8-fastbuild/bin/external/glog/_objs/glog/signalhandler.pic.o \
	bazel-out/k8-fastbuild/bin/external/glog/_objs/glog/symbolize.pic.o \
	bazel-out/k8-fastbuild/bin/external/glog/_objs/glog/utilities.pic.o \
	bazel-out/k8-fastbuild/bin/external/glog/_objs/glog/vlog_is_on.pic.o \
	-Wl,--end-lib \
	-Wl,--start-lib \
  bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags/_objs/gflags/gflags.pic.o \
  bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags/_objs/gflags/gflags_completions.pic.o \
  bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags/_objs/gflags/gflags_reporting.pic.o \
  -Wl,--end-lib \
	-pthread \
	-pthread \
	-lmariadbcpp \
	-lmariadbcpp \
	-lmariadbcpp \
	-lssl \
	-lcrypto \
	-pthread \
	-pthread \
	-lpthread \
	-lpthread \
	-lstdc++ \
	-lm \
	-Ibazel-pelton/external/absl \
	-Ibazel-pelton/bazel-out/k8-fastbuild/bin/external/glog/_virtual_includes/glog/ \
  -Ibazel-pelton/bazel-out/k8-fastbuild/bin/external/com_github_gflags_gflags/_virtual_includes/gflags \
	-Ibazel-pelton/external/gbenchmark/include \
	-I. \
	-Imysql_proxy/src/cpp_wrapper/
cd -
