[package]
name = "owncloud-scenarios"
version = "0.0.1"
authors = ["Justus Adam <dev@justus.science"]

[dependencies]
mysql = "20.1.0"
rand = "0.8.4"
clap = "2.34.0"

[[bin]]
name = "accessible-documents"
path = "accessible_documents.rs"

[[bin]]
name = "granting-access"
path = "granting_access.rs"

[[bin]]
name = "benchmark"
path = "benchmark.rs"