CREATE TABLE students0 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students1 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students2 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students3 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students4 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students5 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students6 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students7 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students8 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students9 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students10 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students11 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students12 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students13 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students14 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students15 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students16 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students17 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students18 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE students19 (ID int, PII_Name text, PRIMARY KEY(ID));
CREATE TABLE assignments0 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments1 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments2 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments3 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments4 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments5 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments6 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments7 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments8 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments9 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments10 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments11 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments12 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments13 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments14 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments15 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments16 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments17 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments18 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE assignments19 (student_id int, assignment_id int, timestamp int, PRIMARY KEY(ID));
CREATE TABLE submissions0 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions1 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions2 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions3 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions4 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions5 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions6 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions7 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions8 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions9 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions10 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions11 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions12 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions13 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions14 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions15 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions16 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions17 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions18 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
CREATE TABLE submissions19 (student_id int, assignment_id int, timestamp int, FOREIGN KEY (student_id) REFERENCES students(ID), FOREIGN KEY (assignment_id) REFERENCES assignments(ID));
