[package]
name = "mysql-log-query-extract"
version = "0.0.1"
authors = ["Justus Adam <dev@justus.science"]

[dependencies]
sqlparser = "0.12.0"
regex = "1.5.4"
lazy_static = "1.4.0"

[[bin]]
name = "mdblogextr"
path = "main.rs"