cc_binary(
  name = "hello_world",
  deps = [
      "//dataflow",
      "@absl//absl/flags:flag",
      "@absl//absl/flags:parse",
      "@glog//:glog",
      "@com_github_gflags_gflags//:gflags"
  ],
  srcs = ["main.cc"],
)
