name: "All Tests and Build"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Dependencies
      run: |
        sudo apt-get install -y gcc-9 g++-9 libsqlite3-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 90 \
                                 --slave /usr/bin/gcc-ar gcc-ar /usr/bin/gcc-ar-9 \
                                 --slave /usr/bin/gcc-nm gcc-nm /usr/bin/gcc-nm-9 \
                                 --slave /usr/bin/gcc-ranlib gcc-ranlib /usr/bin/gcc-ranlib-9 \
                                 --slave /usr/bin/g++ g++ /usr/bin/g++-9
        sudo update-alternatives --set gcc /usr/bin/gcc-9


    - name: Information
      run: |
        bazel --version
        g++ --version
    - name: Build all
      run: bazel build ...

    - name: Test all
      run: bazel test ...
