name: "Tests on Ubuntu"
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    # Docker setup.
    - name: Build docker container
      run: |
        docker build --no-cache -t k9db/latest .

    # Run docker and do one time cargo raze setup.
    - name: Run docker container
      run: |
        docker run --mount type=bind,source=$(pwd),target=/home/k9db --name k9db -d -t k9db/latest
        sleep 20
        docker logs k9db

    # bazel build ...
    - name: Build all
      run: |
        docker exec k9db sh -c "cd /home/k9db && bazel build ..."

    # bazel test all (with encryption; on by default)
    - name: Test all
      run: docker exec k9db sh -c "cd /home/k9db && bazel test ... --test_output=all"

    # bazel test all without encryption
    - name: Test all no encryption
      run: docker exec k9db sh -c "cd /home/k9db && bazel test ... --encryption=off --test_output=all"

